### ISSUE TITLE
Quick CSS fix to make tables look better in posts

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/theodolite#103]
@Floppy this should be quick for you to tackle. Can you please check https://alpha.openaddressesuk.org/blog/2015/02/18/crowdsourcing-challenge-update and make it so that:
- cell content is valigned to the top 
- some border is visible and
- if necessary, the table is made generally more readable perhaps playing with cellpadding and cellspacing?

Ta.

**Comment by Floppy** [comment]
I think this can be done in the markdown... will try it.

**Comment by giacecco** [comment]
I believe Peter tried that already, my guess is that the CSS is missing settings for tables.

**Comment by Floppy** [comment]
I've done it, fix is in https://github.com/OpenAddressesUK/theodolite/commit/5811f740ba280b1726a1a2f6eb29b50d92e6c81c
