### ISSUE TITLE
Open Street Map and validation buttons in the same webpage: misleading?

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/theodolite#104]
This is for @peterkwells in particular, quickly discussed in the office with @Floppy, @pezholio and @pikesley . 

See the screenshot below, showing the current styling of the page we use to get user validation for an address.

![screen shot 2015-02-19 at 10 34 34](https://cloud.githubusercontent.com/assets/303693/6265244/ec04cb90-b823-11e4-85c8-e97910956c5f.png)

I see two problems with it:

a) It may look like we're asking people to validate the address' existence vs the map. It could be read as "is the address where the pointer on the map is?" or "you are a human so you can easily tell if the pointer does or does not fall on no. 65: can you confirm that?"

b) Even if (a) wasn't true, it makes the map a "part" of the validation process, to the point of saying that the validation information is _derived work_ from the map, from a licensing perspective.

What do you think?

Two possible way of solving that: more wording (booo) or hiding the map in the previous page, when one clicks on "Help us improve the UK's address data! Tell us what you know about this address.".

**Comment by peterkwells** [comment]
Good catch, the latter solution (drop the map at this point in the journey) makes sense to me.

Obviously the next step is to flip to a map which is compatible with CC-BY-4.0, possibly even serving that up to those who need it. As verbally discussed this could be "John's map". A roadmap feature is being raised to reassure people that "John's map" doesn't mean John quickly flipping through his collection of paper maps, snapping an image, uploading it and then pressing "GoGoGo" to load the screen/API response.

**Comment by giacecco** [comment]
@floppy see above. For the time being, hiding the map after one clicks on ""Help us improve the UK's address data! Tell us what you know about this address." will be the solution. 

The longer term solution is on the roadmap as https://github.com/OpenAddressesUK/roadmap/issues/83 .

**Comment by Floppy** [comment]
This is irrelevant now, as we're using OS instead.
