### ISSUE TITLE
"Download" under "Documentation"?

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/theodolite#140]
Is it a mistake that we put the "Download" page under the "Documentation" section in the main menu or there's a rationale to it? Thanks.

**Comment by peterkwells** [comment]
It was a deliberate choice done whilst making this update: 

https://github.com/OpenAddressesUK/theodolite/pull/118

Reasons? Bringing together technical material under a single menu item and exploring the thought that we have some different needs which are currently not clearly signposted whilst we come across as overly technical/community. The inspiration came from reviewing other orgs offering APIs and/or bulk downloads.

It's still not right but, I think, is helping me understand the needs.

E.g. key website needs:

Find out more about Open Addresses out of curiousity/fear
Find our more about Open Addresses to see if their services will provide me/my organisation with benefits
Find out more about Open Addresses with intent to use/integrate services
Find out more about Open Addresses to see I can help (develop | add data | etcetera)
etcetera
.

**Comment by giacecco** [comment]
Ok, although if I came to the website to download the data and I did not need the documentation because I knew about it already... I wouldn't find the data! :-) That is how I realised about the change.

Please consider this matter as part of the upcoming work for improving the website.
