### ISSUE TITLE
Hard to read JSON examples

### ISSUE THREAD

**Issue by edent** [OpenAddressesUK/theodolite#38]
The .md has lovely pre-formatted text - the website runs it into one line making it somewhat difficult to follow the examples.

![untitled](https://cloud.githubusercontent.com/assets/837136/5514696/84a53fd0-883e-11e4-86ef-40390dd1f034.png)

**Comment by pezholio** [comment]
Hm. That's odd. What browser are you using? This is how it appears for me in Chrome:

![untitled](https://cloud.githubusercontent.com/assets/109774/5612390/f4880488-94cb-11e4-872c-01db5dcbfd9b.png)

**Comment by edent** [comment]
Was on Firefox. Appears fixed now.

**Comment by pezholio** [comment]
Ah, gotcha. Just noticed that @JeniT fixed it :+1: I'll close your PR in that case. Thanks for pointing this out :smile:
