### ISSUE TITLE
Content negotiation

### ISSUE THREAD

**Issue by alexbilbie** [OpenAddressesUK/theodolite#55]
API clients should be able to negotiate content response types rather than endpoint URIs ending in `.json`.

Even if the only output of the API is currently JSON, I should be able to send `Accept: text/xml` or `Accept: text/html` headers and expect data to be returned in that format or receive an error.

**Comment by pezholio** [comment]
Thanks for the feedback :+1: . Content negotiation works for HTML and JSON as per:

    curl -H "Accept: application/json" http://alpha.openaddressesuk.org/addresses/NVG33L
    curl -H "Accept: text/html" http://alpha.openaddressesuk.org/addresses/NVG33L

But asking for something we don't support, i.e.

    curl -H "Accept: application/xml" http://alpha.openaddressesuk.org/addresses/NVG33L

Results in a 500. This should probably be a 406.
