### ISSUE TITLE
Markdown is not interpreted in article lists

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/theodolite#72]
See screenshot from https://alpha.openaddressesuk.org/about/blog and the preview for the "Upcoming features" blog post at the bottom.

![screen shot 2015-01-22 at 08 15 23](https://cloud.githubusercontent.com/assets/303693/5851937/f03d176a-a20e-11e4-896d-9799509d3d69.png)

**Comment by giacecco** [comment]
@floppy how bad is this to fix? Perhaps I could recommend the team not to use markdown in the top lines of their articles in the meantime :-)

**Comment by Floppy** [comment]
Not very hard. Just need to run it through the markdown processor and then strip the HTML. Need to do it in the gem...

**Comment by Floppy** [comment]
Also, the post ordering is wrong. We could fix that at the same time maybe.

**Comment by Floppy** [comment]
Actually, I'm wrong, it's not in the gem. Won't take a minute.

**Comment by giacecco** [comment]
@Floppy did you fix the ordering, too, in the end? If they're ordered, I don't get what the order is :-)

**Comment by Floppy** [comment]
No, that turned out to be quite a separate job.
